module.exports = {
  projects: [
    '<rootDir>/libs/interfaces',
    '<rootDir>/apps/api',
    '<rootDir>/libs/api-client',
    '<rootDir>/apps/bot',
    '<rootDir>/libs/multi-chain',
    '<rootDir>/libs/redirect-generator',
    '<rootDir>/libs/chain-info',
    '<rootDir>/apps/frontend',
    '<rootDir>/libs/near',
    '<rootDir>/libs/utils',
    '<rootDir>/libs/torus',
    '<rootDir>/libs/baf-contract',
    '<rootDir>/libs/crypto',
    '<rootDir>/libs/base-components',
    '<rootDir>/libs/errors',
    '<rootDir>/libs/t',
    '<rootDir>/libs/core-publishable',
  ],
};
