# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    # TODO: have an initial build step: https://github.com/bafnetwork/baf-wallet-v2/issues/35
    steps:
      - run: |
          runs-on: ubuntu-latest
          sudo apt-get -y install nodejs npm
          npm i
          npm run client-gen
          npx nx test
        