# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push to main, which includes when a PR is merged.
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      workdir: ./apps/api

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: push to api deploy repo
        run: |
          git init
          git branch -M main
          git remote add origin git@github.com:bafnetwork/baf-wallet-deploy-api.git
          git commit -m "deploy"
          git push -u origin main
          rm -rf .git
        working-directory: ${{env.workdir}}
