# this is a basic workflow to help you get started with actions

name: DeployDocs

# controls when the action will run. 
on:
  # triggers the workflow on push to main, which includes when a pr is merged.
  push:
    branches: [ main, deploy-docs ]

  # allows you to run this workflow manually from the actions tab
  workflow_dispatch:

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow contains a single job called "build"
  build:
    # the type of runner that the job will run on
    runs-on: ubuntu-latest


    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@main
      - run: |
          sudo apt-get -y install nodejs npm
          cd docs
          npm i
          npm run build
      - uses: seanmiddleditch/gha-publish-to-git@master
        with:
          repository: bafnetwork/baf-wallet-docs
          branch: main
          github_token: '${{ secrets.github_token  }}'
          github_pat: '${{ secrets.gh_pat }}'
          source_folder: docs/build
